# Write a function nearly equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on. 

def nearly_equal(a, b):
    # Case 1: Strings are identical
    if a == b:
        return False  # no mutation needed
    
    len_a, len_b = len(a), len(b)
    
    # Case 2: Length difference greater than 1 → not nearly equal
    if abs(len_a - len_b) > 1:
        return False
    
    # Case 3: Check substitution (same length, differ by exactly one char)
    if len_a == len_b:
        diff_count = sum(1 for x, y in zip(a, b) if x != y)
        return diff_count == 1
    
    # Case 4: Check insertion/deletion (length differs by 1)
    # Ensure a is the shorter string
    if len_a > len_b:
        a, b = b, a
    
    i = j = 0
    diff_found = False
    while i < len(a) and j < len(b):
        if a[i] != b[j]:
            if diff_found:
                return False
            diff_found = True
            j += 1  # skip one char in longer string
        else:
            i += 1
            j += 1
    return True

# Example usage
print(nearly_equal("cat", "bat"))   # True (substitution)
print(nearly_equal("cat", "cats"))  # True (insertion)
print(nearly_equal("cat", "at"))    # True (deletion)
print(nearly_equal("cat", "dog"))   # False

# Write function to compute gcd, lcm of two numbers. Each function shouldn’t exceed one line.

def gcd(a, b):
    return a if b == 0 else gcd(b, a % b)

def lcm(a, b):
    return (a * b) // gcd(a, b)

# Example usage
num1 = 12
num2 = 15
print(f"GCD of {num1} and {num2} is: {gcd(num1, num2)}")
print(f"LCM of {num1} and {num2} is: {lcm(num1, num2)}")

# OR 

import math

# One-line functions
gcd = lambda a, b: math.gcd(a, b)
lcm = lambda a, b: abs(a*b) // math.gcd(a, b)

# Example usage
print("GCD of 12 and 18:", gcd(12, 18))
print("LCM of 12 and 18:", lcm(12, 18))